###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "johndoe@fakemail.com",
    "password": "123456"
}

###
GET http://localhost:5000/categories
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJKb2huRG9lIiwiZW1haWwiOiJqb2huZG9lQGZha2VtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY5MjYxMzE2M30.-wwwn7u0wc8JzkQNxKeRi-PQVYgZuDIiUl9EzXk8hjo


###
GET http://localhost:5000/items
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJKb2huRG9lIiwiZW1haWwiOiJqb2huZG9lQGZha2VtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY5MjYxMzE2M30.-wwwn7u0wc8JzkQNxKeRi-PQVYgZuDIiUl9EzXk8hjo